# Generated by Django 5.1.7 on 2026-05-13 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservation_prix_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='residences/')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.residence')),
            ],
        ),
    ]
