# Generated by Django 6.0.5 on 2026-06-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reservation_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='reservation',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
