# Generated by Django 6.0.5 on 2026-06-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_reservation_utilisateur_reservation_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='qr_code',
        ),
    ]
